# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-14 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20170414_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.People', verbose_name='作者'),
        ),
    ]
