# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-15 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_artical_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='created_time',
            field=models.DateField(verbose_name='创建时间'),
        ),
    ]
