# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-17 12:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20170415_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='正文'),
        ),
    ]
