# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-20 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20170417_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='headline',
            field=models.CharField(blank=True, max_length=100, verbose_name='标题'),
        ),
    ]
